#ifndef CERTIFICATE_H
#define CERTIFICATE_H

#include <string_view>

namespace network::defaults {

/// Default 2Gis server certificate
constexpr std::string_view certificate[] = {
    "-----BEGIN CERTIFICATE-----\n"
    "MIIFTDCCBDSgAwIBAgIQOCHS6sBCBQLyNFLjMFQtYzANBgkqhkiG9w0BAQsFADCB\n"
    "kDELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G\n"
    "A1UEBxMHU2FsZm9yZDEaMBgGA1UEChMRQ09NT0RPIENBIExpbWl0ZWQxNjA0BgNV\n"
    "BAMTLUNPTU9ETyBSU0EgRG9tYWluIFZhbGlkYXRpb24gU2VjdXJlIFNlcnZlciBD\n"
    "QTAeFw0xODAzMjEwMDAwMDBaFw0yMDA2MjIyMzU5NTlaMFgxITAfBgNVBAsTGERv\n"
    "bWFpbiBDb250cm9sIFZhbGlkYXRlZDEbMBkGA1UECxMSR0dTU0wgV2lsZGNhcmQg\n"
    "U1NMMRYwFAYDVQQDDA0qLmFwaS4yZ2lzLnJ1MIIBIjANBgkqhkiG9w0BAQEFAAOC\n"
    "AQ8AMIIBCgKCAQEA21FR4LSqbYc31q5+QCb/21CiV1pOsATvCWEM8RcNZG4hy+Aw\n"
    "3raU7C2tZxpLWgKFlka9maBzcXwzG9/8duZM2bWOu+c0tXM4pgiHP/gc0S14in/K\n"
    "iBzVr3+TC/JtbhdzVA21igWG7N0AYlWSy6Dx0U0VVORYZY4XiNTOhG/ZL0GOAkBe\n"
    "ZCj7+KEFymZU+vIgbr137PbADpnrDKmiQtvMD/IVYetCcBB4V4wXaBvfoCY+bYKu\n"
    "uJFWjcvVOjqji4o1hYJpra284Lw+vVvhqNiNc+KUvnFFWy94/8VwnA2TvjLE0pyG\n"
    "iiFoVOG/ml21xslSVDauTP080OPfbRP1W22sIwIDAQABo4IB1zCCAdMwHwYDVR0j\n"
    "BBgwFoAUkK9qOpRaC9iQ6hJWc99DtDoo2ucwHQYDVR0OBBYEFHj2aKUFW/hu7g7O\n"
    "GkkCOEYn5gpZMA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB0GA1UdJQQW\n"
    "MBQGCCsGAQUFBwMBBggrBgEFBQcDAjBPBgNVHSAESDBGMDoGCysGAQQBsjEBAgIH\n"
    "MCswKQYIKwYBBQUHAgEWHWh0dHBzOi8vc2VjdXJlLmNvbW9kby5jb20vQ1BTMAgG\n"
    "BmeBDAECATBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vY3JsLmNvbW9kb2NhLmNv\n"
    "bS9DT01PRE9SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJlU2VydmVyQ0EuY3JsMIGF\n"
    "BggrBgEFBQcBAQR5MHcwTwYIKwYBBQUHMAKGQ2h0dHA6Ly9jcnQuY29tb2RvY2Eu\n"
    "Y29tL0NPTU9ET1JTQURvbWFpblZhbGlkYXRpb25TZWN1cmVTZXJ2ZXJDQS5jcnQw\n"
    "JAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmNvbW9kb2NhLmNvbTAlBgNVHREEHjAc\n"
    "gg0qLmFwaS4yZ2lzLnJ1ggthcGkuMmdpcy5ydTANBgkqhkiG9w0BAQsFAAOCAQEA\n"
    "iYIMSijSXcINnwKgYpWoN0/Q0fRnsdgZsPdprnR9386CDwix8+2k6OFDsbsfnd6a\n"
    "/a8q0tpcT0bkq6RM4k5BUz0c7YLsYaBT1EpPxa/F8aXF66vY2sRUrwI7PI3SAGis\n"
    "O+S4Awp6J2I6E26jVQn4hpS4Yj8h3PT+rrvDn6JEVFIKnTVPkxHDSvDLcVhIcT7p\n"
    "gXIRDrBYaCkBXNo5/Fk0Tk0gXi1DONtL7mhrps1x2FB5vWJutOq5iKfNkvHQT3si\n"
    "wY/m/Us0C/SaXjcUuBJiBO9mmUv7RBFvumgbvnt9bjcB0L6nZSaAdF5PhaLsrdvJ\n"
    "tpes2XrTdVYces0/z7NVPw==\n"
    "-----END CERTIFICATE-----\n"};
} // namespace network::defaults
#endif // CERTIFICATE_H
